"""Add invalid_messages table

Revision ID: c5578fe2109a
Revises: 9dc5eb210b90
Create Date: 2025-07-23 13:31:39.980861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5578fe2109a'
down_revision: Union[str, Sequence[str], None] = '9dc5eb210b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invalid_messages')
    # ### end Alembic commands ###
